//Long list of moveId names
const masterMoves = {
  0: "Unknown Move",
  1: "Miscellaneous",
  2: "Jab",
  3: "Jab",
  4: "Jab",
  5: "Rapid Jabs",
  6: "Dash Attack",
  7: "Forward Tilt",
  8: "Up Tilt",
  9: "Down Tilt",
  10: "Forward Smash",
  11: "Up Smash",
  12: "Down Smash",
  13: "Neutral Air",
  14: "Forward Air",
  15: "Back Air",
  16: "Up Air",
  17: "Down Air",
  18: "Neutral B",
  19: "Side B",
  20: "Up B",
  21: "Down B",
  22: "Unknown Move",
  23: "Unknown Move",
  24: "Unknown Move",
  25: "Unknown Move",
  26: "Unknown Move",
  27: "Unknown Move",
  28: "Unknown Move",
  29: "Unknown Move",
  30: "Unknown Move",
  31: "Unknown Move",
  32: "Unknown Move",
  33: "Unknown Move",
  34: "Unknown Move",
  35: "Unknown Move",
  36: "Unknown Move",
  37: "Unknown Move",
  38: "Unknown Move",
  39: "Unknown Move",
  40: "Unknown Move",
  41: "Unknown Move",
  42: "Unknown Move",
  43: "Unknown Move",
  44: "Unknown Move",
  45: "Unknown Move",
  46: "Unknown Move",
  47: "Unknown Move",
  48: "Unknown Move",
  49: "Unknown Move",
  50: "Getup Attack",
  51: "Getup Attack (Slow)",
  52: "Grab Pummel",
  53: "Forward Throw",
  54: "Back Throw",
  55: "Up Throw",
  56: "Down Throw",
  57: "Unknown Move",
  58: "Unknown Move",
  59: "Unknown Move",
  60: "Unknown Move",
  61: "Edge Attack (Slow)",
  62: "Edge Attack",
  63: "Unknown Move",
  64: "Unknown Move",
  65: "Unknown Move",
  66: "Unknown Move",
  67: "Unknown Move",
  68: "Unknown Move",
  69: "Unknown Move",
  70: "Unknown Move",
  71: "Unknown Move",
  72: "Unknown Move",
  73: "Unknown Move",
  74: "Unknown Move",
  75: "Unknown Move",
  76: "Unknown Move",
  77: "Unknown Move",
  78: "Unknown Move",
  79: "Unknown Move",
  80: "Unknown Move",
  81: "Unknown Move",
  82: "Unknown Move",
  83: "Unknown Move",
  84: "Unknown Move",
  85: "Unknown Move",
  86: "Unknown Move",
  87: "Unknown Move",
  88: "Unknown Move",
  89: "Unknown Move",
  90: "Unknown Move",
  91: "Unknown Move",
  92: "Unknown Move",
  93: "Unknown Move",
  94: "Unknown Move",
  95: "Unknown Move",
  96: "Unknown Move",
  97: "Unknown Move",
  98: "Unknown Move",
  99: "Unknown Move",
  100: "Unknown Move",
};

export default masterMoves;
